#ansible-galaxy collection install kewlfft.aur
---
- name: Clean Manjaro
  hosts: localhost
  #become: yes

  pre_tasks:
    # - name: Create the `aur_builder` user
    #   become: yes
    #   ansible.builtin.user:
    #     create_home: yes
    #     name: aur_builder
    #     group: wheel

    # - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    #   become: yes
    #   ansible.builtin.lineinfile:
    #     path: /etc/sudoers.d/11-install-aur_builder
    #     line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    #     create: yes
    #     validate: "/usr/sbin/visudo -cf %s"

    # - name: Clone YAY repo
    #   become: yes
    #   become_user: aur_builder
    #   git:
    #     repo: https://aur.archlinux.org/yay.git
    #     dest: /tmp/yay_install
    #     accept_hostkey: yes
    #   ignore_errors: yes

  tasks:
    - name: Installing initial packages
      become: yes
      community.general.pacman:
        name:
          - bat
          - exa
          - neofetch
        state: absent
        force: true

    # - name: install packages from aur
    #   become: yes
    #   become_method: sudo
    #   become_user: aur_builder
    #   ignore_errors: yes
    #   kewlfft.aur.aur:
    #     use: makepkg
    #     name:
    #       - yay
    #     state: present
