#ansible-galaxy collection install kewlfft.aur
---
- name: Provision Fresh Manjaro
  hosts: localhost
  #become: yes

  pre_tasks:
    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        create_home: yes
        name: aur_builder
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        validate: "/usr/sbin/visudo -cf %s"

    # - name: Clone YAY repo
    #   become: yes
    #   become_user: aur_builder
    #   git:
    #     repo: https://aur.archlinux.org/yay.git
    #     dest: /tmp/yay_install
    #     accept_hostkey: yes
    #   ignore_errors: yes

    # - name: Update & upgrade system `pacman -Syu`
    #   become: yes
    #   community.general.pacman:
    #     update_cache: true
    #     upgrade: true

    # - name: Upgrade the system using yay, only act on AUR packages.
    #   kewlfft.aur.aur:
    #     upgrade: yes
    #     use: yay
    #     aur_only: yes

  tasks:
    # - name: Installing initial packages
    #   become: yes
    #   community.general.pacman:
    #     name:
    #       - bat
    #       - exa
    #       - neofetch
    #     state: present

    - name: install packages from aur
      become: yes
      become_method: sudo
      become_user: aur_builder
      ignore_errors: yes
      kewlfft.aur.aur:
        use: makepkg
        name:
          - yay
        state: present

    # - name: Run the equivalent of "pacman -Rdd", force remove package baz
    #   community.general.pacman:
    #     name: yay
    #     state: absent
    #     force: true

    #- name: Clone pass repo
    #  become: yes
    #  become_user: "{{ user.newUsername }}"
    #  git:
    #    repo: git@github.com:marnyg/pass.git
    #    dest: ~/.local/share/password-store
    #    accept_hostkey: yes
    #  ignore_errors: yes

    # - name: make user
    #   become: yes
    #   user:
    #     name: aur_builder
    #     group: wheel

    # - name: add sudo privlages
    #   become: yes
    #   lineinfile:
    #     path: /etc/sudoers.d/11-install-aur_builder
    #     line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    #     create: yes
    #     validate: 'visudo -cf %s'

    # - name: install packages from aur
    #   become: yes
    #   become_user: aur_builder
    #   ignore_errors: yes
    #   aur:
    #     use: yay
    #     name:
    #       - lf-bin
    #       - font-symbola
    #       - zsh-fast-syntax-highlighting
    #       - hunspell-nb
    #       - ttf-iosevka
    #     state: present

    #      - name: set up pam to start gnome keyring at login
    #        become: yes
    #        pamd:
    #          name: login
    #          type: auth
    #          control: include
    #          module_path: system-local-login
    #          new_type: auth
    #          new_control: optional
    #          new_module_path: pam_gnome_keyring.so
    #          state: after
    #
    #      - name: set up pam to start gnome keyring at login
    #        become: yes
    #        pamd:
    #          name: login
    #          type: session
    #          control: include
    #          module_path: system-local-login
    #          new_type: session
    #          new_control: optional
    #          new_module_path: pam_gnome_keyring.so
    #          state: after
    #          module_arguments: auto_start
  # vars:
  #   user:
  #     name: man
  #     pass : 1a2b3c45
  #     newUsername: mar
  # roles:
  #     - kewlfft.aur
